"""Init tables et check capacity

Revision ID: 14fb7bdea1ce
Revises: 
Create Date: 2026-10-03 19:51:06.189696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14fb7bdea1ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.Enum('permanent_exhibition', 'theater', 'guided_tour', name='event_type'), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_email', sa.String(length=320), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', name='reservation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('booked_seats', sa.Integer(), nullable=False),
    sa.CheckConstraint('booked_seats <= max_capacity', name='check_seats_capacity'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_event_id'), 'sessions', ['event_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_category', sa.Enum('adult', 'child', 'group', 'school', name='ticket_category'), nullable=False),
    sa.Column('is_scanned', sa.Boolean(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_reservation_id'), 'tickets', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_tickets_session_id'), 'tickets', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_session_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_reservation_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_sessions_event_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('reservations')
    op.drop_table('events')
    # ### end Alembic commands ###
