"""event price per ticket category

Revision ID: 5e59dc6519d3
Revises: 14fb7bdea1ce
Create Date: 2026-10-04 19:52:55.587264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e59dc6519d3'
down_revision: Union[str, Sequence[str], None] = '14fb7bdea1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('price_adult', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('events', sa.Column('price_child', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('events', sa.Column('price_group', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('events', sa.Column('price_school', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'price_school')
    op.drop_column('events', 'price_group')
    op.drop_column('events', 'price_child')
    op.drop_column('events', 'price_adult')
    # ### end Alembic commands ###
